name: 'Print message'
description: 'Print a message'
inputs:
  message:  # id of input
    description: 'Message to print'
    required: true
    default: 'Be original!!'
outputs:
  same_messager:
    description: "Message to print"
    value: ${{ steps.return-message.outputs.message-out }}
runs:
  using: "composite"
  steps:
    - name: Return message
      id: return-message
      run: echo "message-out=$(echo $MESSAGE_IN)" >> $GITHUB_OUTPUT
      shell: bash
      env:
        MESSAGE_IN: ${{ inputs.message }}