name: Docker CD Pipeline

on:
  push:
    branches:
      - master
  schedule: 
    -cron: '*/5 * * * *'

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Print message
      id: call_message
      uses: ./.github/actions/print_message
      with:
        message: I like to read my own message
    - run: echo "message:" "$MESSAGE_OUT"
      name: print output
      shell: bash
      env:
        MESSAGE_OUT: ${{ steps.call_message.outputs.same_message }}
      
        