name: Message flow

on:
  push:
    branches:
      - master
  # schedule: 
    # - cron: '*/5 * * * *'

jobs:
  print_message:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Print message
      id: call_message
      uses: ./.github/actions/print_message
      with:
        message: I like to read my own message
    - name: print output
      run: echo "message:" "$MESSAGE_OUT"
      shell: bash
      env:
        MESSAGE_OUT: ${{ steps.call_message.outputs.same_message }}
    - name: was_the_same
      if: ${{ steps.call_message.outputs.same_message }} == 'I like to read my own message'
      shell: bash
      run: echo was the same

      
        