name: Docker CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:latest
          context: exercise_3

  deployment_dev:
    runs-on: ubuntu-latest
    environment: ${{ matrix.env }}
    strategy:
          matrix:
             env: [dev, int, pro]
          max-parallel: 1
    steps:
      - name: deploy ${{ matrix.env }}
        run: sleep 5
