name: Docker CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: deploy_flow
    steps:
      - uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:latest
          context: exercise_3
  deployment_dev:
    runs-on: ubuntu-latest
    environment: dev
    concurrency: deploy_flow
    steps:
      - name: deploy dev
        run: sleep 5
  deployment_int:
    runs-on: ubuntu-latest
    environment: int
    concurrency: deploy_flow
    steps:
      - name: deploy dev
        run: sleep 5
  deployment_pro:
    runs-on: ubuntu-latest
    environment: pro
    concurrency: deploy_flow
    steps:
      - name: deploy dev
        run: sleep 5